version: '3.8'
services: 
  database:
    image: mongo
#    environment: 
#      - MONGO_INITDB_ROOT_USERNAME=user
#      - MONGO_INITDB_ROOT_PASSWORD=132
    ports:
      - 27017:27017
    volumes: 
      - my_data:/data/db
  node-web:
    restart: always 
    build: 
      context: .
      dockerfile: ./images/Dockerfile
    depends_on: 
      - database
    volumes: 
      - /app/node_modules
      - ./app:/app 
    ports: 
      - "5000:5000"
  
volumes: 
  my_data: 
